### ISSUE TITLE
出處

### ISSUE THREAD

**Issue by zeteticl** [Bluebear171/coc_adv_index#1]
呃,HI,我是GOOGLE  DRIVE模組 的擁有者
那個內容算私人分享給群朋友,
如果你抽中間的MOD 的連結進行分享,希望你順便分享這些出來:D

香港TRPG研究社
https://www.facebook.com/groups/HKTRPG

香港面團專區
http://www.goddessfantasy.net/bbs/index.php?board=1400.0

TRPG百科
https://www.hktrpg.com/

《COC自動角色卡7 版》
https://docs.google.com/spreadsheets/d/1B6V92cSJ0zbWb91g_DKE66ztAJl8kAaUKcZWV2_4CS4/edit?usp=sharing

《COC自動角色卡6 版》
https://docs.google.com/spreadsheets/d/169gMo0K_JmZmD9WDwU8kIePtaXhrc7tbDwPHEem5xdk/edit?usp=sharing

**Comment by Bluebear171** [comment]
好啊好啊我也在我的Readme 這裡加上你給的資料吧^-^
